spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/conf
#        git:
#          uri: https://github.com/spring-cloud-samples/config-repo
#          searchPaths: classpath:/conf
server:
  port: 2002 # 2BCD:2001=ZK;2002=CONF;2003=CA;3BCD=API;4BCD=UI
